import grpc
import time
from concurrent import futures

# Note: In a real environment, these are generated by:
# python -m grpc_tools.protoc -I./proto --python_out=. --grpc_python_out=. ./proto/arkhe_network.proto
try:
    from .proto import arkhe_network_pb2
    from .proto import arkhe_network_pb2_grpc
except ImportError:
    # Mocking for demonstration/tutorial purposes if not compiled
    class MockServicer: pass
    arkhe_network_pb2_grpc = type('Mock', (object,), {'ArkheHypergraphServicer': MockServicer})
    arkhe_network_pb2 = type('Mock', (object,), {
        'HandoverResponse': lambda **kwargs: kwargs,
        'CoherenceMetrics': lambda **kwargs: kwargs
    })

class ArkheHypergraphServicer(arkhe_network_pb2_grpc.ArkheHypergraphServicer):
    def __init__(self, node_id):
        self.node_id = node_id
        self.phi_target = 0.847
        self.ledger = []

    def SubmitHandover(self, request, context):
        print(f"📡 [{self.node_id}] Handover recebido de {request.node_id}")

        # Validação do Proof-of-Coherence
        if request.phi_achieved >= self.phi_target:
            print(f"✅ Handover Validado! Φ = {request.phi_achieved:.4f}")
            # Registrar no ledger local Ω+∞
            self.ledger.append(request.block_hash)

            return arkhe_network_pb2.HandoverResponse(
                accepted=True,
                message="Ressonância confirmada.",
                network_phi_target=self.phi_target + 0.001 # Aumenta dificuldade marginalmente
            )
        else:
            print(f"❌ Handover Rejeitado. Φ baixo: {request.phi_achieved:.4f}")
            return arkhe_network_pb2.HandoverResponse(
                accepted=False,
                message="Decoerência detectada.",
                network_phi_target=self.phi_target
            )

    def GetNodeCoherence(self, request, context):
        return arkhe_network_pb2.CoherenceMetrics(
            current_phi=0.912,
            active_entanglements=42,
            operational_mode="STABILIZE"
        )

def serve_arkhe_node(node_id="ARKHE_RIO_01", port="50051"):
    server = grpc.server(futures.ThreadPoolExecutor(max_workers=10))
    # If using real generated code:
    # arkhe_network_pb2_grpc.add_ArkheHypergraphServicer_to_server(
    #    ArkheHypergraphServicer(node_id), server
    # )
    server.add_insecure_port(f'[::]:{port}')
    # server.start()
    print(f"🌍 Nó Arkhe(N) [{node_id}] Online e aguardando conexões quânticas (gRPC) na porta {port}...")
    # server.wait_for_termination()
    return server

if __name__ == '__main__':
    serve_arkhe_node()
