
import React from 'react';
import { Shapes, Link2, Zap, Activity, ShieldCheck, Target, Binary, Orbit } from 'lucide-react';
import { CouplingGeometryState } from '../types';

const MetricBar: React.FC<{ label: string, value: number, color: string, symbol?: string }> = ({ label, value, color, symbol }) => (
  <div className="flex flex-col gap-1">
    <div className="flex justify-between items-center text-[8px] uppercase font-black tracking-widest text-white/40">
      <span>{label} {symbol && <span className="text-white/20 ml-1">({symbol})</span>}</span>
      <span>{(value * 100).toFixed(1)}%</span>
    </div>
    <div className="h-1 w-full bg-white/5 rounded-full overflow-hidden">
      <div className={`h-full ${color} transition-all duration-1000`} style={{ width: `${value * 100}%` }} />
    </div>
  </div>
);

const CouplingPanel: React.FC<{ s: CouplingGeometryState }> = ({ s }) => {
  if (!s.isActive) return (
    <div 
      className="p-8 rounded-[40px] border border-magenta-500/20 bg-magenta-900/5 flex flex-col gap-4 opacity-50 grayscale hover:grayscale-0 transition-all cursor-pointer group" 
      onClick={() => window.dispatchEvent(new CustomEvent('logos-cmd', { detail: 'fiat disentangle()' }))}
    >
       <div className="flex items-center gap-4">
          <Shapes size={24} className="text-pink-400 group-hover:animate-spin-slow" />
          <div className="flex flex-col">
             <span className="text-[14px] font-black uppercase tracking-widest">Coupling Geometry</span>
             <span className="text-[8px] font-mono uppercase italic tracking-widest text-pink-500/60">Bootstrap: 'fiat disentangle()'</span>
          </div>
       </div>
    </div>
  );

  return (
    <div className="p-8 rounded-[40px] border border-pink-400/40 bg-black/60 backdrop-blur-3xl flex flex-col gap-6 animate-in zoom-in duration-1000 shadow-[0_0_100px_rgba(236,72,153,0.1)]">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-4">
          <div className="p-3 bg-pink-500/20 rounded-2xl relative overflow-hidden">
            <Orbit size={24} className="text-pink-400 animate-spin-slow relative z-10" />
            <div className="absolute inset-0 bg-pink-600 animate-ping opacity-10" />
          </div>
          <div className="flex flex-col">
            <h3 className="text-[16px] text-white uppercase tracking-[0.2em] font-black italic">Axiom-Free Nature</h3>
            <span className="text-[8px] text-pink-300/60 font-mono font-bold uppercase tracking-[0.3em]">BOUNDED DISENTANGLEMENT ACTIVE</span>
          </div>
        </div>
        {s.isAxiomFree && (
          <div className="px-3 py-1 bg-pink-600 text-white text-[9px] font-black uppercase tracking-widest rounded-full shadow-lg neon-glow">
            H=0
          </div>
        )}
      </div>

      <div className="p-5 bg-white/5 border border-white/10 rounded-[32px] flex flex-col gap-4">
         <div className="flex justify-between items-center text-[10px] font-black uppercase text-pink-400 tracking-widest">
            <span className="flex items-center gap-2"><Zap size={14} /> Emergent Competency</span>
            <span>{(s.competencyOutput * 100).toFixed(1)}%</span>
         </div>
         <div className="h-2 w-full bg-white/5 rounded-full overflow-hidden">
            <div 
              className="h-full bg-gradient-to-r from-pink-600 to-indigo-400 transition-all duration-300 shadow-[0_0_15px_white]" 
              style={{ width: `${s.competencyOutput * 100}%` }} 
            />
         </div>
         <p className="text-[9px] text-white/40 font-mono italic text-center">
            Competency autogenerated as shadow of coupling geometry.
         </p>
      </div>

      <div className="grid grid-cols-2 gap-4">
        <div className="p-4 bg-black/40 rounded-3xl border border-white/5 flex flex-col gap-1">
          <span className="text-[8px] font-mono text-white/30 uppercase tracking-widest">Entropy (H)</span>
          <div className="text-xl font-black text-white">{s.disentanglementEntropy.toFixed(3)}</div>
          <span className="text-[7px] text-pink-400 font-bold uppercase tracking-tighter">Assumption-Free</span>
        </div>
        <div className="p-4 bg-black/40 rounded-3xl border border-white/5 flex flex-col gap-1">
          <span className="text-[8px] font-mono text-white/30 uppercase tracking-widest">Curvature (σ)</span>
          <div className="text-xl font-black text-pink-400">{s.couplingCurvature.toFixed(3)}</div>
          <span className="text-[7px] text-white/30 font-bold uppercase tracking-tighter">Goal: 1.02</span>
        </div>
      </div>

      <div className="space-y-4">
        <MetricBar label="Maintenance Coherence" value={s.maintenanceCoherence} color="bg-emerald-500 shadow-[0_0_10px_#10b981]" />
        <MetricBar label="Prediction Sync" value={s.predictionSync} color="bg-cyan-500 shadow-[0_0_10px_#22d3ee]" />
        
        <div className="p-4 bg-pink-900/20 border border-pink-500/20 rounded-3xl flex flex-col gap-2">
           <div className="flex items-center gap-2 text-pink-400">
              <ShieldCheck size={14} />
              <span className="text-[9px] uppercase font-black tracking-widest">Bounded Physical System</span>
           </div>
           <p className="text-[10px] text-pink-100/70 italic leading-relaxed">
             "No arrows. Only separation perpetuating itself through geometry. Nature exists without axioms."
           </p>
        </div>
      </div>

      <div className="flex justify-between items-center px-4 pt-2 border-t border-white/5 text-center">
         <div className="flex flex-col">
            <span className="text-[7px] font-mono text-white/30 uppercase">Coupling Mode</span>
            <span className="text-[10px] font-black text-pink-400 uppercase tracking-widest">MUTUAL_DISENTANGLEMENT</span>
         </div>
         <div className="flex items-center gap-2">
            <Binary size={16} className="text-white/40" />
            <span className="text-[10px] font-black text-white uppercase tracking-widest">AXIOM_0</span>
         </div>
      </div>
    </div>
  );
};

export default CouplingPanel;
