//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnnealingSpec) DeepCopyInto(out *AnnealingSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnnealingSpec.
func (in *AnnealingSpec) DeepCopy() *AnnealingSpec {
	if in == nil {
		return nil
	}
	out := new(AnnealingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlockRange) DeepCopyInto(out *BlockRange) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlockRange.
func (in *BlockRange) DeepCopy() *BlockRange {
	if in == nil {
		return nil
	}
	out := new(BlockRange)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CarnotLimitSpec) DeepCopyInto(out *CarnotLimitSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CarnotLimitSpec.
func (in *CarnotLimitSpec) DeepCopy() *CarnotLimitSpec {
	if in == nil {
		return nil
	}
	out := new(CarnotLimitSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChainIntegration) DeepCopyInto(out *ChainIntegration) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChainIntegration.
func (in *ChainIntegration) DeepCopy() *ChainIntegration {
	if in == nil {
		return nil
	}
	out := new(ChainIntegration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChargingSpec) DeepCopyInto(out *ChargingSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChargingSpec.
func (in *ChargingSpec) DeepCopy() *ChargingSpec {
	if in == nil {
		return nil
	}
	out := new(ChargingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigMapRef) DeepCopyInto(out *ConfigMapRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigMapRef.
func (in *ConfigMapRef) DeepCopy() *ConfigMapRef {
	if in == nil {
		return nil
	}
	out := new(ConfigMapRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Coordinates) DeepCopyInto(out *Coordinates) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Coordinates.
func (in *Coordinates) DeepCopy() *Coordinates {
	if in == nil {
		return nil
	}
	out := new(Coordinates)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CoreResourceSpec) DeepCopyInto(out *CoreResourceSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CoreResourceSpec.
func (in *CoreResourceSpec) DeepCopy() *CoreResourceSpec {
	if in == nil {
		return nil
	}
	out := new(CoreResourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DestinationSpec) DeepCopyInto(out *DestinationSpec) {
	*out = *in
	if in.Timestamp != nil {
		in, out := &in.Timestamp, &out.Timestamp
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DestinationSpec.
func (in *DestinationSpec) DeepCopy() *DestinationSpec {
	if in == nil {
		return nil
	}
	out := new(DestinationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EmbodiedAgent) DeepCopyInto(out *EmbodiedAgent) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EmbodiedAgent.
func (in *EmbodiedAgent) DeepCopy() *EmbodiedAgent {
	if in == nil {
		return nil
	}
	out := new(EmbodiedAgent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EmbodiedAgent) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EmbodiedAgentList) DeepCopyInto(out *EmbodiedAgentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EmbodiedAgent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EmbodiedAgentList.
func (in *EmbodiedAgentList) DeepCopy() *EmbodiedAgentList {
	if in == nil {
		return nil
	}
	out := new(EmbodiedAgentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EmbodiedAgentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EmbodiedAgentSpec) DeepCopyInto(out *EmbodiedAgentSpec) {
	*out = *in
	out.Environment = in.Environment
	out.Learning = in.Learning
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EmbodiedAgentSpec.
func (in *EmbodiedAgentSpec) DeepCopy() *EmbodiedAgentSpec {
	if in == nil {
		return nil
	}
	out := new(EmbodiedAgentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EmbodiedAgentStatus) DeepCopyInto(out *EmbodiedAgentStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EmbodiedAgentStatus.
func (in *EmbodiedAgentStatus) DeepCopy() *EmbodiedAgentStatus {
	if in == nil {
		return nil
	}
	out := new(EmbodiedAgentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EmergencyTzinor) DeepCopyInto(out *EmergencyTzinor) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EmergencyTzinor.
func (in *EmergencyTzinor) DeepCopy() *EmergencyTzinor {
	if in == nil {
		return nil
	}
	out := new(EmergencyTzinor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EmergencyTzinor) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EmergencyTzinorList) DeepCopyInto(out *EmergencyTzinorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EmergencyTzinor, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EmergencyTzinorList.
func (in *EmergencyTzinorList) DeepCopy() *EmergencyTzinorList {
	if in == nil {
		return nil
	}
	out := new(EmergencyTzinorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EmergencyTzinorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EmergencyTzinorSpec) DeepCopyInto(out *EmergencyTzinorSpec) {
	*out = *in
	if in.AuthorizedNodes != nil {
		in, out := &in.AuthorizedNodes, &out.AuthorizedNodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EmergencyTzinorSpec.
func (in *EmergencyTzinorSpec) DeepCopy() *EmergencyTzinorSpec {
	if in == nil {
		return nil
	}
	out := new(EmergencyTzinorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EmergencyTzinorStatus) DeepCopyInto(out *EmergencyTzinorStatus) {
	*out = *in
	if in.LastActivation != nil {
		in, out := &in.LastActivation, &out.LastActivation
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EmergencyTzinorStatus.
func (in *EmergencyTzinorStatus) DeepCopy() *EmergencyTzinorStatus {
	if in == nil {
		return nil
	}
	out := new(EmergencyTzinorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EntanglementStatus) DeepCopyInto(out *EntanglementStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EntanglementStatus.
func (in *EntanglementStatus) DeepCopy() *EntanglementStatus {
	if in == nil {
		return nil
	}
	out := new(EntanglementStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EntropyShield) DeepCopyInto(out *EntropyShield) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EntropyShield.
func (in *EntropyShield) DeepCopy() *EntropyShield {
	if in == nil {
		return nil
	}
	out := new(EntropyShield)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EntropyShield) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EntropyShieldList) DeepCopyInto(out *EntropyShieldList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EntropyShield, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EntropyShieldList.
func (in *EntropyShieldList) DeepCopy() *EntropyShieldList {
	if in == nil {
		return nil
	}
	out := new(EntropyShieldList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EntropyShieldList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentSpec) DeepCopyInto(out *EnvironmentSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentSpec.
func (in *EnvironmentSpec) DeepCopy() *EnvironmentSpec {
	if in == nil {
		return nil
	}
	out := new(EnvironmentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Era) DeepCopyInto(out *Era) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Era.
func (in *Era) DeepCopy() *Era {
	if in == nil {
		return nil
	}
	out := new(Era)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Era) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EraList) DeepCopyInto(out *EraList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Era, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EraList.
func (in *EraList) DeepCopy() *EraList {
	if in == nil {
		return nil
	}
	out := new(EraList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EraList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EraSpec) DeepCopyInto(out *EraSpec) {
	*out = *in
	out.BlockRange = in.BlockRange
	out.Resources = in.Resources
	out.Annealing = in.Annealing
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EraSpec.
func (in *EraSpec) DeepCopy() *EraSpec {
	if in == nil {
		return nil
	}
	out := new(EraSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EraStatus) DeepCopyInto(out *EraStatus) {
	*out = *in
	if in.LastThawTime != nil {
		in, out := &in.LastThawTime, &out.LastThawTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EraStatus.
func (in *EraStatus) DeepCopy() *EraStatus {
	if in == nil {
		return nil
	}
	out := new(EraStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExpectedOutput) DeepCopyInto(out *ExpectedOutput) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExpectedOutput.
func (in *ExpectedOutput) DeepCopy() *ExpectedOutput {
	if in == nil {
		return nil
	}
	out := new(ExpectedOutput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GKPAtom) DeepCopyInto(out *GKPAtom) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GKPAtom.
func (in *GKPAtom) DeepCopy() *GKPAtom {
	if in == nil {
		return nil
	}
	out := new(GKPAtom)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GKPAtom) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GKPAtomList) DeepCopyInto(out *GKPAtomList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GKPAtom, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GKPAtomList.
func (in *GKPAtomList) DeepCopy() *GKPAtomList {
	if in == nil {
		return nil
	}
	out := new(GKPAtomList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GKPAtomList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GKPAtomSpec) DeepCopyInto(out *GKPAtomSpec) {
	*out = *in
	out.TrapConfiguration = in.TrapConfiguration
	out.GkpEncoding = in.GkpEncoding
	if in.VibrationalModes != nil {
		in, out := &in.VibrationalModes, &out.VibrationalModes
		*out = make([]VibrationalMode, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GKPAtomSpec.
func (in *GKPAtomSpec) DeepCopy() *GKPAtomSpec {
	if in == nil {
		return nil
	}
	out := new(GKPAtomSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GKPAtomStatus) DeepCopyInto(out *GKPAtomStatus) {
	*out = *in
	out.Entanglement = in.Entanglement
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GKPAtomStatus.
func (in *GKPAtomStatus) DeepCopy() *GKPAtomStatus {
	if in == nil {
		return nil
	}
	out := new(GKPAtomStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitRef) DeepCopyInto(out *GitRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitRef.
func (in *GitRef) DeepCopy() *GitRef {
	if in == nil {
		return nil
	}
	out := new(GitRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GkpEncodingSpec) DeepCopyInto(out *GkpEncodingSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GkpEncodingSpec.
func (in *GkpEncodingSpec) DeepCopy() *GkpEncodingSpec {
	if in == nil {
		return nil
	}
	out := new(GkpEncodingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeatSourceSpec) DeepCopyInto(out *HeatSourceSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeatSourceSpec.
func (in *HeatSourceSpec) DeepCopy() *HeatSourceSpec {
	if in == nil {
		return nil
	}
	out := new(HeatSourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImplantLocationSpec) DeepCopyInto(out *ImplantLocationSpec) {
	*out = *in
	out.Coordinates = in.Coordinates
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImplantLocationSpec.
func (in *ImplantLocationSpec) DeepCopy() *ImplantLocationSpec {
	if in == nil {
		return nil
	}
	out := new(ImplantLocationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IoQTDevice) DeepCopyInto(out *IoQTDevice) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IoQTDevice.
func (in *IoQTDevice) DeepCopy() *IoQTDevice {
	if in == nil {
		return nil
	}
	out := new(IoQTDevice)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IoQTDevice) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IoQTDeviceList) DeepCopyInto(out *IoQTDeviceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IoQTDevice, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IoQTDeviceList.
func (in *IoQTDeviceList) DeepCopy() *IoQTDeviceList {
	if in == nil {
		return nil
	}
	out := new(IoQTDeviceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IoQTDeviceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IoQTDeviceSpec) DeepCopyInto(out *IoQTDeviceSpec) {
	*out = *in
	out.QcaConfiguration = in.QcaConfiguration
	out.ImplantLocation = in.ImplantLocation
	out.PowerSource = in.PowerSource
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IoQTDeviceSpec.
func (in *IoQTDeviceSpec) DeepCopy() *IoQTDeviceSpec {
	if in == nil {
		return nil
	}
	out := new(IoQTDeviceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IoQTDeviceStatus) DeepCopyInto(out *IoQTDeviceStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IoQTDeviceStatus.
func (in *IoQTDeviceStatus) DeepCopy() *IoQTDeviceStatus {
	if in == nil {
		return nil
	}
	out := new(IoQTDeviceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeyDistributionSpec) DeepCopyInto(out *KeyDistributionSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeyDistributionSpec.
func (in *KeyDistributionSpec) DeepCopy() *KeyDistributionSpec {
	if in == nil {
		return nil
	}
	out := new(KeyDistributionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LambdaT) DeepCopyInto(out *LambdaT) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LambdaT.
func (in *LambdaT) DeepCopy() *LambdaT {
	if in == nil {
		return nil
	}
	out := new(LambdaT)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LambdaT) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LambdaTList) DeepCopyInto(out *LambdaTList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LambdaT, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LambdaTList.
func (in *LambdaTList) DeepCopy() *LambdaTList {
	if in == nil {
		return nil
	}
	out := new(LambdaTList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LambdaTList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LambdaTSpec) DeepCopyInto(out *LambdaTSpec) {
	*out = *in
	out.Trigger = in.Trigger
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LambdaTSpec.
func (in *LambdaTSpec) DeepCopy() *LambdaTSpec {
	if in == nil {
		return nil
	}
	out := new(LambdaTSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LambdaTStatus) DeepCopyInto(out *LambdaTStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LambdaTStatus.
func (in *LambdaTStatus) DeepCopy() *LambdaTStatus {
	if in == nil {
		return nil
	}
	out := new(LambdaTStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LatticeSpec) DeepCopyInto(out *LatticeSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LatticeSpec.
func (in *LatticeSpec) DeepCopy() *LatticeSpec {
	if in == nil {
		return nil
	}
	out := new(LatticeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LearningSpec) DeepCopyInto(out *LearningSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LearningSpec.
func (in *LearningSpec) DeepCopy() *LearningSpec {
	if in == nil {
		return nil
	}
	out := new(LearningSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MicrocavitySpec) DeepCopyInto(out *MicrocavitySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MicrocavitySpec.
func (in *MicrocavitySpec) DeepCopy() *MicrocavitySpec {
	if in == nil {
		return nil
	}
	out := new(MicrocavitySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NeuralIntegration) DeepCopyInto(out *NeuralIntegration) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NeuralIntegration.
func (in *NeuralIntegration) DeepCopy() *NeuralIntegration {
	if in == nil {
		return nil
	}
	out := new(NeuralIntegration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OnChainRef) DeepCopyInto(out *OnChainRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OnChainRef.
func (in *OnChainRef) DeepCopy() *OnChainRef {
	if in == nil {
		return nil
	}
	out := new(OnChainRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OriginSpec) DeepCopyInto(out *OriginSpec) {
	*out = *in
	if in.Timestamp != nil {
		in, out := &in.Timestamp, &out.Timestamp
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OriginSpec.
func (in *OriginSpec) DeepCopy() *OriginSpec {
	if in == nil {
		return nil
	}
	out := new(OriginSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PllSpec) DeepCopyInto(out *PllSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PllSpec.
func (in *PllSpec) DeepCopy() *PllSpec {
	if in == nil {
		return nil
	}
	out := new(PllSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolaritonBattery) DeepCopyInto(out *PolaritonBattery) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolaritonBattery.
func (in *PolaritonBattery) DeepCopy() *PolaritonBattery {
	if in == nil {
		return nil
	}
	out := new(PolaritonBattery)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolaritonBattery) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolaritonBatteryList) DeepCopyInto(out *PolaritonBatteryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PolaritonBattery, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolaritonBatteryList.
func (in *PolaritonBatteryList) DeepCopy() *PolaritonBatteryList {
	if in == nil {
		return nil
	}
	out := new(PolaritonBatteryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PolaritonBatteryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolaritonBatterySpec) DeepCopyInto(out *PolaritonBatterySpec) {
	*out = *in
	out.Microcavity = in.Microcavity
	out.Charging = in.Charging
	out.Storage = in.Storage
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolaritonBatterySpec.
func (in *PolaritonBatterySpec) DeepCopy() *PolaritonBatterySpec {
	if in == nil {
		return nil
	}
	out := new(PolaritonBatterySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolaritonBatteryStatus) DeepCopyInto(out *PolaritonBatteryStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolaritonBatteryStatus.
func (in *PolaritonBatteryStatus) DeepCopy() *PolaritonBatteryStatus {
	if in == nil {
		return nil
	}
	out := new(PolaritonBatteryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostQuantumCrypto) DeepCopyInto(out *PostQuantumCrypto) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostQuantumCrypto.
func (in *PostQuantumCrypto) DeepCopy() *PostQuantumCrypto {
	if in == nil {
		return nil
	}
	out := new(PostQuantumCrypto)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PostQuantumCrypto) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostQuantumCryptoList) DeepCopyInto(out *PostQuantumCryptoList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PostQuantumCrypto, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostQuantumCryptoList.
func (in *PostQuantumCryptoList) DeepCopy() *PostQuantumCryptoList {
	if in == nil {
		return nil
	}
	out := new(PostQuantumCryptoList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PostQuantumCryptoList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostQuantumCryptoSpec) DeepCopyInto(out *PostQuantumCryptoSpec) {
	*out = *in
	out.KeyDistribution = in.KeyDistribution
	out.Lattice = in.Lattice
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostQuantumCryptoSpec.
func (in *PostQuantumCryptoSpec) DeepCopy() *PostQuantumCryptoSpec {
	if in == nil {
		return nil
	}
	out := new(PostQuantumCryptoSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostQuantumCryptoStatus) DeepCopyInto(out *PostQuantumCryptoStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostQuantumCryptoStatus.
func (in *PostQuantumCryptoStatus) DeepCopy() *PostQuantumCryptoStatus {
	if in == nil {
		return nil
	}
	out := new(PostQuantumCryptoStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PowerSourceSpec) DeepCopyInto(out *PowerSourceSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PowerSourceSpec.
func (in *PowerSourceSpec) DeepCopy() *PowerSourceSpec {
	if in == nil {
		return nil
	}
	out := new(PowerSourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProgrammabilitySpec) DeepCopyInto(out *ProgrammabilitySpec) {
	*out = *in
	if in.InstructionSet != nil {
		in, out := &in.InstructionSet, &out.InstructionSet
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProgrammabilitySpec.
func (in *ProgrammabilitySpec) DeepCopy() *ProgrammabilitySpec {
	if in == nil {
		return nil
	}
	out := new(ProgrammabilitySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProofInput) DeepCopyInto(out *ProofInput) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProofInput.
func (in *ProofInput) DeepCopy() *ProofInput {
	if in == nil {
		return nil
	}
	out := new(ProofInput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProofStatus) DeepCopyInto(out *ProofStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProofStatus.
func (in *ProofStatus) DeepCopy() *ProofStatus {
	if in == nil {
		return nil
	}
	out := new(ProofStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProofVerifier) DeepCopyInto(out *ProofVerifier) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProofVerifier.
func (in *ProofVerifier) DeepCopy() *ProofVerifier {
	if in == nil {
		return nil
	}
	out := new(ProofVerifier)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProofVerifier) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProofVerifierList) DeepCopyInto(out *ProofVerifierList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ProofVerifier, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProofVerifierList.
func (in *ProofVerifierList) DeepCopy() *ProofVerifierList {
	if in == nil {
		return nil
	}
	out := new(ProofVerifierList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProofVerifierList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProofVerifierSpec) DeepCopyInto(out *ProofVerifierSpec) {
	*out = *in
	in.SourceRef.DeepCopyInto(&out.SourceRef)
	out.Input = in.Input
	out.ExpectedOutput = in.ExpectedOutput
	out.VerifierConfig = in.VerifierConfig
	out.ChainIntegration = in.ChainIntegration
	out.NeuralIntegration = in.NeuralIntegration
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProofVerifierSpec.
func (in *ProofVerifierSpec) DeepCopy() *ProofVerifierSpec {
	if in == nil {
		return nil
	}
	out := new(ProofVerifierSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProofVerifierStatus) DeepCopyInto(out *ProofVerifierStatus) {
	*out = *in
	if in.Proof != nil {
		in, out := &in.Proof, &out.Proof
		*out = new(ProofStatus)
		**out = **in
	}
	if in.ZKCertificate != nil {
		in, out := &in.ZKCertificate, &out.ZKCertificate
		*out = new(ZKCertificateStatus)
		**out = **in
	}
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = new(VerificationMetrics)
		**out = **in
	}
	if in.OnChainRef != nil {
		in, out := &in.OnChainRef, &out.OnChainRef
		*out = new(OnChainRef)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProofVerifierStatus.
func (in *ProofVerifierStatus) DeepCopy() *ProofVerifierStatus {
	if in == nil {
		return nil
	}
	out := new(ProofVerifierStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QcaConfiguration) DeepCopyInto(out *QcaConfiguration) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QcaConfiguration.
func (in *QcaConfiguration) DeepCopy() *QcaConfiguration {
	if in == nil {
		return nil
	}
	out := new(QcaConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuantumNeuralNetwork) DeepCopyInto(out *QuantumNeuralNetwork) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuantumNeuralNetwork.
func (in *QuantumNeuralNetwork) DeepCopy() *QuantumNeuralNetwork {
	if in == nil {
		return nil
	}
	out := new(QuantumNeuralNetwork)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *QuantumNeuralNetwork) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuantumNeuralNetworkList) DeepCopyInto(out *QuantumNeuralNetworkList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]QuantumNeuralNetwork, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuantumNeuralNetworkList.
func (in *QuantumNeuralNetworkList) DeepCopy() *QuantumNeuralNetworkList {
	if in == nil {
		return nil
	}
	out := new(QuantumNeuralNetworkList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *QuantumNeuralNetworkList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuantumNeuralNetworkSpec) DeepCopyInto(out *QuantumNeuralNetworkSpec) {
	*out = *in
	out.Training = in.Training
	if in.HardwareBackend != nil {
		in, out := &in.HardwareBackend, &out.HardwareBackend
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuantumNeuralNetworkSpec.
func (in *QuantumNeuralNetworkSpec) DeepCopy() *QuantumNeuralNetworkSpec {
	if in == nil {
		return nil
	}
	out := new(QuantumNeuralNetworkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuantumNeuralNetworkStatus) DeepCopyInto(out *QuantumNeuralNetworkStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuantumNeuralNetworkStatus.
func (in *QuantumNeuralNetworkStatus) DeepCopy() *QuantumNeuralNetworkStatus {
	if in == nil {
		return nil
	}
	out := new(QuantumNeuralNetworkStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceRef) DeepCopyInto(out *SourceRef) {
	*out = *in
	if in.ConfigMapRef != nil {
		in, out := &in.ConfigMapRef, &out.ConfigMapRef
		*out = new(ConfigMapRef)
		**out = **in
	}
	if in.GitRef != nil {
		in, out := &in.GitRef, &out.GitRef
		*out = new(GitRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceRef.
func (in *SourceRef) DeepCopy() *SourceRef {
	if in == nil {
		return nil
	}
	out := new(SourceRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageSpec) DeepCopyInto(out *StorageSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageSpec.
func (in *StorageSpec) DeepCopy() *StorageSpec {
	if in == nil {
		return nil
	}
	out := new(StorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThermalEngine) DeepCopyInto(out *ThermalEngine) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThermalEngine.
func (in *ThermalEngine) DeepCopy() *ThermalEngine {
	if in == nil {
		return nil
	}
	out := new(ThermalEngine)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ThermalEngine) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThermalEngineList) DeepCopyInto(out *ThermalEngineList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ThermalEngine, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThermalEngineList.
func (in *ThermalEngineList) DeepCopy() *ThermalEngineList {
	if in == nil {
		return nil
	}
	out := new(ThermalEngineList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ThermalEngineList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThermalEngineSpec) DeepCopyInto(out *ThermalEngineSpec) {
	*out = *in
	out.HeatSource = in.HeatSource
	out.WorkOutput = in.WorkOutput
	in.Programmability.DeepCopyInto(&out.Programmability)
	out.CarnotLimit = in.CarnotLimit
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThermalEngineSpec.
func (in *ThermalEngineSpec) DeepCopy() *ThermalEngineSpec {
	if in == nil {
		return nil
	}
	out := new(ThermalEngineSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThermalEngineStatus) DeepCopyInto(out *ThermalEngineStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThermalEngineStatus.
func (in *ThermalEngineStatus) DeepCopy() *ThermalEngineStatus {
	if in == nil {
		return nil
	}
	out := new(ThermalEngineStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThetaRhythm) DeepCopyInto(out *ThetaRhythm) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThetaRhythm.
func (in *ThetaRhythm) DeepCopy() *ThetaRhythm {
	if in == nil {
		return nil
	}
	out := new(ThetaRhythm)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ThetaRhythm) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThetaRhythmList) DeepCopyInto(out *ThetaRhythmList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ThetaRhythm, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThetaRhythmList.
func (in *ThetaRhythmList) DeepCopy() *ThetaRhythmList {
	if in == nil {
		return nil
	}
	out := new(ThetaRhythmList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ThetaRhythmList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrainingSpec) DeepCopyInto(out *TrainingSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrainingSpec.
func (in *TrainingSpec) DeepCopy() *TrainingSpec {
	if in == nil {
		return nil
	}
	out := new(TrainingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrapConfiguration) DeepCopyInto(out *TrapConfiguration) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrapConfiguration.
func (in *TrapConfiguration) DeepCopy() *TrapConfiguration {
	if in == nil {
		return nil
	}
	out := new(TrapConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TriggerSpec) DeepCopyInto(out *TriggerSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TriggerSpec.
func (in *TriggerSpec) DeepCopy() *TriggerSpec {
	if in == nil {
		return nil
	}
	out := new(TriggerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Tzinor) DeepCopyInto(out *Tzinor) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Tzinor.
func (in *Tzinor) DeepCopy() *Tzinor {
	if in == nil {
		return nil
	}
	out := new(Tzinor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Tzinor) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TzinorList) DeepCopyInto(out *TzinorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Tzinor, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TzinorList.
func (in *TzinorList) DeepCopy() *TzinorList {
	if in == nil {
		return nil
	}
	out := new(TzinorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TzinorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TzinorSpec) DeepCopyInto(out *TzinorSpec) {
	*out = *in
	in.Origin.DeepCopyInto(&out.Origin)
	in.Destination.DeepCopyInto(&out.Destination)
	out.Pll = in.Pll
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TzinorSpec.
func (in *TzinorSpec) DeepCopy() *TzinorSpec {
	if in == nil {
		return nil
	}
	out := new(TzinorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TzinorStatus) DeepCopyInto(out *TzinorStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TzinorStatus.
func (in *TzinorStatus) DeepCopy() *TzinorStatus {
	if in == nil {
		return nil
	}
	out := new(TzinorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VerCore) DeepCopyInto(out *VerCore) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VerCore.
func (in *VerCore) DeepCopy() *VerCore {
	if in == nil {
		return nil
	}
	out := new(VerCore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VerCore) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VerCoreList) DeepCopyInto(out *VerCoreList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VerCore, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VerCoreList.
func (in *VerCoreList) DeepCopy() *VerCoreList {
	if in == nil {
		return nil
	}
	out := new(VerCoreList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VerCoreList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VerCoreSpec) DeepCopyInto(out *VerCoreSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VerCoreSpec.
func (in *VerCoreSpec) DeepCopy() *VerCoreSpec {
	if in == nil {
		return nil
	}
	out := new(VerCoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VerCoreStatus) DeepCopyInto(out *VerCoreStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VerCoreStatus.
func (in *VerCoreStatus) DeepCopy() *VerCoreStatus {
	if in == nil {
		return nil
	}
	out := new(VerCoreStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VerificationMetrics) DeepCopyInto(out *VerificationMetrics) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VerificationMetrics.
func (in *VerificationMetrics) DeepCopy() *VerificationMetrics {
	if in == nil {
		return nil
	}
	out := new(VerificationMetrics)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VerifierConfig) DeepCopyInto(out *VerifierConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VerifierConfig.
func (in *VerifierConfig) DeepCopy() *VerifierConfig {
	if in == nil {
		return nil
	}
	out := new(VerifierConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VibrationalMode) DeepCopyInto(out *VibrationalMode) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VibrationalMode.
func (in *VibrationalMode) DeepCopy() *VibrationalMode {
	if in == nil {
		return nil
	}
	out := new(VibrationalMode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkOutputSpec) DeepCopyInto(out *WorkOutputSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkOutputSpec.
func (in *WorkOutputSpec) DeepCopy() *WorkOutputSpec {
	if in == nil {
		return nil
	}
	out := new(WorkOutputSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZKCertificateStatus) DeepCopyInto(out *ZKCertificateStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZKCertificateStatus.
func (in *ZKCertificateStatus) DeepCopy() *ZKCertificateStatus {
	if in == nil {
		return nil
	}
	out := new(ZKCertificateStatus)
	in.DeepCopyInto(out)
	return out
}
